from .healthReq import HealthReq
from .userRegReq import UserRegReq
from .userLoginReq import UserLoginReq
from .userInfoReq import UserInfoReq
from .friendRequestReq import FriendRequestReq
from .friendListReq import FriendListReq
from .createPostReq import CreatePostReq
from .sendMessageReq import SendMessageReq
from .getPostsReq import GetPostsReq
from .reportMessageReq import ReportMessageReq
from .responseToFriendRequestReq import ResponseToFriendRequestReq
from .chatHistoryReq import ChatHistoryReq
from .reportPostReq import ReportPostReq
